### ISSUE TITLE
Switch over to another voice. Microsoft bob bad

### ISSUE THREAD

**Issue by blazecoding2009** [TeamBitsEUREKA/Mayday#3]
Please please please switch from microsoft bob, hes depressing and no emotions

Please test your code

**Comment by cmdgames** [comment]
kind of fixed(swapped ms-bob for google translate voice(usegoogleapi=True))

**Comment by blazecoding2009** [comment]
so some improvements to this would be just tuning ngl

**Comment by bulutthecat** [comment]
I am working on making another branch for a more advanced and easy to use API, it might require some modification although I do think it will be worth it.

**Comment by bulutthecat** [comment]
> kind of fixed(swapped ms-bob for google translate voice(usegoogleapi=True))

we want to move away from online processing, as it slows down our application by quite alot and is unnecessary. although this is a major improvement over other alternatives.

**Comment by bulutthecat** [comment]
ok the new API is working, but there are major issues with the Google TTS engine with the new fixes, extra testing is needed, this issue is still relevant.

**Comment by bulutthecat** [comment]
finished, all bugs are solved, until further notice this topic is closed
